"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _new_arrival_card from './new-arrival-card.bones.json'
import _best_seller_card from './best-seller-card.bones.json'

registerBones({
  "new-arrival-card": _new_arrival_card,
  "best-seller-card": _best_seller_card,
})
